<?php
return array (
  10 => 
  array (
    'catid' => '10',
    'siteid' => '1',
    'type' => '1',
    'modelid' => '0',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '10,16',
    'catname' => '关于我们',
    'style' => '',
    'image' => '',
    'description' => '关于我们！！！！',
    'parentdir' => '',
    'catdir' => 'guanyuwomen',
    'url' => 'http://www.mrjt.com/index.php?m=content&c=index&a=lists&catid=10',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"ishtml":"0","template_list":"mrjt","page_template":"page_gywm","meta_title":"","meta_keywords":"","meta_description":"","category_ruleid":"6","show_ruleid":"","repeatchargedays":"1"}',
    'listorder' => '10',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'guanyuwomen',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => '0',
    'content_ishtml' => NULL,
    'category_ruleid' => '6',
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
  11 => 
  array (
    'catid' => '11',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '3',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '11',
    'catname' => '集团产业',
    'style' => '',
    'image' => '',
    'description' => '这是集团产业',
    'parentdir' => '',
    'catdir' => 'jituanchanye',
    'url' => 'http://www.mrjt.com/index.php?m=content&c=index&a=lists&catid=11',
    'items' => '5',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"mrjt","category_template":"category_news","list_template":"list_cyjt","show_template":"show_cyjt","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '11',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'jituanchanye',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  12 => 
  array (
    'catid' => '12',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '3',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '12',
    'catname' => '新闻动态',
    'style' => '',
    'image' => '',
    'description' => '这是新闻动态！！！！',
    'parentdir' => '',
    'catdir' => 'xinwendongtai',
    'url' => 'http://www.mrjt.com/index.php?m=content&c=index&a=lists&catid=12',
    'items' => '4',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"mrjt","category_template":"category_news","list_template":"list_xwdt","show_template":"show_xwdt","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '12',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'xinwendongtai',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  13 => 
  array (
    'catid' => '13',
    'siteid' => '1',
    'type' => '1',
    'modelid' => '0',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '13',
    'catname' => '联系我们',
    'style' => '',
    'image' => '',
    'description' => '联系我们！！！',
    'parentdir' => '',
    'catdir' => 'lianxiwomen',
    'url' => 'http://www.mrjt.com/index.php?m=content&c=index&a=lists&catid=13',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"ishtml":"0","template_list":"mrjt","page_template":"page_lxwm","meta_title":"","meta_keywords":"","meta_description":"","category_ruleid":"6","show_ruleid":"","repeatchargedays":"1"}',
    'listorder' => '13',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'lianxiwomen',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => '0',
    'content_ishtml' => NULL,
    'category_ruleid' => '6',
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
  16 => 
  array (
    'catid' => '16',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '2',
    'parentid' => '10',
    'arrparentid' => '0,10',
    'child' => '0',
    'arrchildid' => '16',
    'catname' => 'php面向对象',
    'style' => '',
    'image' => '',
    'description' => 'php面向对象',
    'parentdir' => '/',
    'catdir' => 'phpmianxiangduixiang',
    'url' => 'http://www.mrjt.com/index.php?m=content&c=index&a=lists&catid=16',
    'items' => '1',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"mrjt","category_template":"category","list_template":"list_xz","show_template":"show_xz","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '16',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'phpmianxiangduixiang',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
);
?>